# Generated by Django 6.1 on 2026-09-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        ("products", "0006_alter_category_unique_together_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.UniqueConstraint(
                fields=("order", "product"), name="unique_product_per_order"
            ),
        ),
    ]
