# Generated by Django 6.1 on 2026-09-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_orderitem_unique_product_per_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
