# Generated by Django 6.1 on 2026-09-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("MOCK", "Mock"), ("MERCADOPAGO", "Mercado Pago")],
                default="MOCK",
                max_length=30,
            ),
        ),
    ]
