# Generated by Django 6.1 on 2026-09-24 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='init_point',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
